ktor:
    application:
        modules:
            - br.usp.eventUSP.ApplicationKt.module
    deployment:
        port: 8080

datasource:
    url: "jdbc:mysql://localhost:3306/eventusp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
    driver: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "root"
